# Generated by Django 5.0.6 on 2025-06-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_priceprediction_prediction_lower_bound_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdata',
            name='ma_30d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='ma_7d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_hist',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_line',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='macd_signal',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='marketdata',
            name='rsi',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
